namespace EToto.Web.Services;

public class LanguageService
{
    private string _currentLanguage = "pt-BR";

    public string CurrentLanguage => _currentLanguage;
    public bool IsPortuguese => _currentLanguage == "pt-BR";

    public event Action? OnLanguageChanged;

    public void SetLanguage(string language)
    {
        if (_currentLanguage == language) return;
        _currentLanguage = language;
        OnLanguageChanged?.Invoke();
    }

    public string this[string key] => GetTranslation(key);

    private string GetTranslation(string key)
    {
        var dict = _currentLanguage == "en-US" ? _en : _pt;
        return dict.TryGetValue(key, out var value) ? value : key;
    }

    // ──────────────────────────────────────────────────────────────────
    //  PORTUGUÊS (pt-BR)
    // ──────────────────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> _pt = new()
    {
        // ── Navegação ──────────────────────────────────────────────────
        ["nav.search"]           = "Pesquisar",
        ["nav.equipments"]       = "Equipamentos",
        ["nav.users"]            = "Usuários",
        ["nav.plants"]           = "Plantas",
        ["nav.logout"]           = "Sair",
        ["nav.restricted_admin"] = "Acesso restrito ao administrador",
        ["nav.restricted_super"] = "Acesso restrito ao Super Gestor",
        ["nav.no_plant"]         = "Sem planta",
        ["nav.plant_label"]      = "Planta",
        ["nav.date"]             = "Data",
        ["nav.operator"]         = "Operador",
        ["nav.environment"]      = "Ambiente",
        ["nav.sections"]         = "Seções",
        ["nav.audit"]            = "Auditoria",
        ["nav.reports"]          = "Relatórios",
        ["nav.campaigns"]        = "Campanhas",

        // ── Login ──────────────────────────────────────────────────────
        ["login.login"]          = "Login",
        ["login.password"]       = "Senha",
        ["login.plant"]          = "Planta",
        ["login.select"]         = "Selecione...",
        ["login.enter"]          = "Entrar",
        ["login.signing_in"]     = "Entrando...",
        ["login.direct_access"]  = "Acesso direto",
        ["login.field_blocked"]  = "Campo bloqueado para este usuário",
        ["login.auth_error"]     = "Não foi possível autenticar. Verifique os dados e tente novamente.",
        // Vínculo / validade de acesso (#2)
        ["login.access_expired"] = "Seu acesso está vencido. Procure a Segurança do Trabalho da planta responsável para renovar.",
        ["login.access_expiring_today"] = "Seu acesso vence hoje. Procure a Segurança do Trabalho para renovar.",
        ["login.access_expiring_in_days"] = "Seu acesso vence em {0} dia(s). Procure a Segurança do Trabalho para renovar.",
        // Treinamento (#3)
        ["login.training_expired"] = "Seu treinamento LOTOTO está vencido. Procure a Segurança do Trabalho da planta responsável para renovar.",
        ["login.training_expiring_today"] = "Seu treinamento LOTOTO vence hoje. Procure a Segurança do Trabalho para renovar.",
        ["login.training_expiring_in_days"] = "Seu treinamento LOTOTO vence em {0} dia(s). Procure a Segurança do Trabalho para renovar.",
        ["login.continue"]       = "Continuar",

        // ── Ambiente ───────────────────────────────────────────────────
        ["env.homologacao"]      = "Ambiente de Homologação",

        // ── Comum ──────────────────────────────────────────────────────
        ["common.save"]          = "Salvar alterações",
        ["common.register"]      = "Cadastrar",
        ["common.delete"]        = "Excluir",
        ["common.edit"]          = "Editar",
        ["common.close"]         = "Fechar",
        ["common.view"]          = "Visualizar",
        ["common.yes_delete"]    = "Sim, excluir",
        ["common.no"]            = "Não",
        ["common.confirm_delete"]= "Confirmar exclusão",
        ["common.success"]       = "Sucesso",
        ["common.error"]         = "Erro",
        ["common.attention"]     = "Atenção",
        ["common.page"]          = "Página",
        ["common.of"]            = "de",
        ["common.active"]        = "Ativo",
        ["common.inactive"]      = "Inativo",
        ["common.active_f"]      = "Ativa",
        ["common.inactive_f"]    = "Inativa",
        ["common.actions"]       = "Ações",
        ["common.search"]        = "Pesquisar",
        ["common.loading"]       = "Carregando...",
        ["common.processing"]    = "Processando...",
        ["common.clear"]         = "Limpar",
        ["common.cancel_edit"]   = "Cancelar edição",
        ["common.select_state"]  = "-- selecione o estado --",
        ["common.cancel_edit_title"] = "Cancelar edição",
        ["common.confirm"]       = "Confirmar",
        ["common.select_all"]    = "Selecionar todos",
        // Timeline (Histórico) – ações armazenadas em PT no banco
        ["timeline.action.created"]     = "Criado",
        ["timeline.action.started"]     = "Iniciado",
        ["timeline.action.cancelled"]   = "Cancelado",
        ["timeline.action.start_unlock"] = "Início do Desbloqueio",
        ["timeline.action.finalized"]   = "Finalizado",
        ["timeline.action.modified"]    = "Modificado",
        ["timeline.action.deleted"]     = "Excluído",
        ["timeline.action.deactivated"] = "Inativado",
        ["timeline.action.activated"]   = "Ativado",

        // ── Home ───────────────────────────────────────────────────────
        ["home.title"]                  = "Consulta de energias perigosas por equipamento",
        ["home.filters"]                = "Filtros de pesquisa",
        ["home.plant"]                  = "Planta",
        ["home.select_plant"]           = "Selecione...",
        ["home.all_my_plants"]          = "Todas as minhas plantas",
        ["home.tag"]                    = "Tag do equipamento",
        ["home.tag_placeholder"]        = "Ex.: FMTZ-100-BC11",
        ["home.name_desc"]              = "Nome / descrição do equipamento",
        ["home.name_placeholder"]       = "Parte do nome...",
        ["home.energy_type"]            = "Tipo de energia",
        ["home.energy_type_placeholder"]= "Ex.: Elétrica, Pneumática...",
        ["home.energy_desc"]            = "Descrição da energia perigosa",
        ["home.energy_desc_placeholder"]= "Parte da descrição...",
        ["home.isolation_tag"]          = "TAG disp. isolamento",
        ["home.isolation_tag_ph"]       = "TAG dispositivo",
        ["home.device_location"]        = "Localização dispositivo",
        ["home.device_location_ph"]     = "Painel, área, sala...",
        ["home.isolation_device"]       = "Dispositivo de isolamento",
        ["home.isolation_device_ph"]    = "Disjuntor, válvula, etc.",
        ["home.lockout"]                = "Bloqueio",
        ["home.lockout_ph"]             = "Tipo de bloqueio",
        ["home.zero_energy"]            = "Verificação de energia zero",
        ["home.zero_energy_ph"]         = "Parte do texto da verificação...",
        ["home.test"]                   = "Teste",
        ["home.test_ph"]                = "Parte do texto do teste...",
        ["home.results"]                = "Resultados",
        ["home.equipment_found"]        = "equipamento(s) encontrado(s)",
        ["home.not_found_filter"]       = "Nenhum equipamento encontrado para os filtros",
        ["home.loading"]                = "A carregar equipamentos...",
        ["home.searching"]              = "A pesquisar...",
        ["home.no_records"]             = "Nenhum registo para os filtros informados.",
        ["home.view_image"]             = "Ver imagem",
        ["home.image_unavailable"]      = "Imagem não disponível.",
        ["home.notes"]                  = "Notas",
        ["home.no_notes"]               = "Nenhuma nota encontrada para esta imagem.",
        ["home.table.identification"]   = "I. Identificação",
        ["home.table.energy_control"]   = "II. Controlo energias",
        ["home.table.tag"]              = "Tag",
        ["home.table.equipment"]        = "Equip.",
        ["home.table.number"]           = "Nº",
        ["home.table.energy_type"]      = "Tipo energ.",
        ["home.table.img"]              = "Img",
        ["home.table.energy_desc"]      = "Desc. energ.",
        ["home.table.isolation_tag"]    = "TAG disp.",
        ["home.table.loc_device"]       = "Loc. disp.",
        ["home.table.device"]           = "Disp.",
        ["home.table.lockout"]          = "Bloq.",
        ["home.table.zero_energy"]      = "Verif. energ. zero",
        ["home.table.test"]             = "Teste",
        ["home.table.plant"]            = "Planta",
        // Toasts
        ["home.toast.select_plant"]     = "Selecione a planta para pesquisar os equipamentos.",
        ["home.toast.no_plant_claim"]   = "Planta não encontrada nas claims do utilizador.",
        ["home.toast.load_error"]       = "Erro ao carregar equipamentos.",

        // ── Usuários ──────────────────────────────────────────────────
        ["users.register"]              = "Cadastrar Usuário",
        ["users.edit"]                  = "Editar Usuário",
        ["users.login_field"]           = "Login",
        ["users.full_name"]             = "Nome completo",
        ["users.password"]              = "Senha",
        ["users.password_hint"]         = "Deixe em branco para manter a senha atual.",
        ["users.access_profile"]        = "Perfil de acesso",
        ["users.access_profiles"]       = "Perfis de acesso (selecione um ou mais)",
        ["users.profile_super_exclusive"] = "Super Gestor não pode ser combinado com outros perfis.",
        // Vínculo Funcionário/Terceiro (#2)
        ["users.bond_type"]             = "Tipo de vínculo",
        ["users.bond_employee"]         = "Funcionário",
        ["users.bond_contractor"]       = "Parceiro",
        ["users.company_name"]          = "Empresa parceira",
        ["users.access_validity"]       = "Validade do acesso",
        ["users.access_validity_hint"]  = "Máximo de 6 meses a partir de hoje.",
        ["users.col_bond"]              = "Vínculo",
        ["users.col_validity"]          = "Validade",
        ["users.validity_expired"]      = "Vencido",
        ["users.validity_expiring"]     = "Vencendo (≤30d)",
        ["users.validity_active"]       = "Vigente",
        ["users.toast.company_required"] = "Para Parceiro, informe o nome da empresa.",
        ["users.toast.validity_required"] = "Para Parceiro, informe a data de validade do acesso.",
        ["users.toast.validity_max_6m"] = "A validade de acesso não pode exceder 6 meses.",
        // Toolbox de sub-abas da página de Usuários (#4)
        ["users.tab.registration"]      = "Cadastro",
        ["users.tab.revalidation"]      = "Revalidação",
        ["users.tab.audit"]             = "Auditoria",
        ["users.tab.reports"]           = "Relatórios",
        ["users.plants_select"]         = "Plantas (selecione uma ou mais)",
        ["users.admin_restriction"]     = "Como administrador, você só pode associar usuários às suas plantas",
        ["users.select_plant_required"] = "Selecione pelo menos uma planta",
        ["users.active"]                = "Usuário ativo",
        ["users.search"]                = "Pesquisa de Usuários",
        ["users.search_placeholder"]    = "Login, nome, perfil, vínculo, empresa ou planta...",
        ["users.found"]                 = "usuário(s) encontrado(s)",
        ["users.not_found"]             = "Nenhum usuário encontrado",
        ["users.col_login"]             = "Login",
        ["users.col_name"]              = "Nome",
        ["users.col_profile"]           = "Perfil",
        ["users.col_profiles"]          = "Perfis",
        ["users.col_plants"]            = "Plantas",
        ["users.col_active"]            = "Ativo",
        ["users.all_plants"]            = "Todas as plantas",
        ["users.no_plant"]              = "Sem planta",
        ["users.no_records"]            = "Nenhum usuário encontrado para os filtros informados.",
        ["users.delete_confirm_text"]   = "Tem certeza que deseja excluir o usuário",
        ["users.profile_user"]          = "Usuário",
        ["users.profile_admin"]         = "Administrador",
        ["users.profile_super"]         = "Super Gestor",
        ["users.profile_final"]         = "Líder de Bloqueio",
        ["users.profile_central"]       = "Comando Central",
        ["users.training_completed"]    = "Treinamento LOTOTO concluído",
        // Validade do treinamento (#3)
        ["users.training_validity"]     = "Validade do treinamento",
        ["users.training_validity_hint"] = "Preenchida automaticamente: data do treinamento + 2 anos.",
        ["users.col_training"]          = "Treinamento",
        ["users.training_not_required"] = "Não exigido para este perfil",
        // Toasts
        ["users.toast.login_required"]  = "O login é obrigatório.",
        ["users.toast.only_super"]      = "Apenas Super Gestores podem cadastrar Super Gestores.",
        ["users.toast.profile_required"] = "Selecione pelo menos um perfil.",
        ["users.toast.profile_super_exclusive"] = "Super Gestor não pode ser combinado com outros perfis.",
        ["users.toast.select_plant"]    = "Selecione pelo menos uma planta.",
        ["users.toast.own_plants_only"] = "Você só pode associar usuários às suas plantas.",
        ["users.toast.duplicate"]       = "Já existe um usuário com este login para uma das plantas selecionadas.",
        ["users.toast.no_permission"]   = "Você não tem permissão para editar este usuário.",
        ["users.toast.saved"]           = "Usuário atualizado com sucesso.",
        ["users.toast.registered"]      = "Usuário cadastrado com sucesso.",
        ["users.toast.save_error"]      = "Erro ao salvar usuário.",
        ["users.toast.deleted"]         = "Usuário excluído com sucesso.",
        ["users.toast.delete_error"]    = "Erro ao excluir usuário.",
        // Auditoria de cadastro (#1c)
        ["users.audit_title"]           = "Auditoria do cadastro",
        ["users.created_by"]            = "Criado por",
        ["users.updated_by"]            = "Alterado por",
        ["users.audit_at"]              = "em",
        ["users.audit_unknown"]         = "—",

        // ── Plantas ───────────────────────────────────────────────────
        ["plants.register"]             = "Cadastrar Planta",
        ["plants.edit"]                 = "Editar Planta",
        ["plants.name"]                 = "Nome da Planta",
        ["plants.code"]                 = "Código",
        ["plants.location"]             = "Localização",
        ["plants.active"]               = "Planta ativa",
        ["plants.search"]               = "Pesquisa de Plantas",
        ["plants.search_placeholder"]   = "Nome, código ou localização...",
        ["plants.found"]                = "planta(s) encontrada(s)",
        ["plants.not_found"]            = "Nenhuma planta encontrada",
        ["plants.col_code"]             = "Código",
        ["plants.col_name"]             = "Nome",
        ["plants.col_location"]         = "Localização",
        ["plants.col_active"]           = "Ativa",
        ["plants.active_badge"]         = "Ativa",
        ["plants.inactive_badge"]       = "Inativa",
        ["plants.no_records"]           = "Nenhuma planta encontrada para os filtros informados.",
        ["plants.delete_confirm_text"]  = "Tem certeza que deseja excluir",
        // Toasts
        ["plants.toast.saved"]          = "Planta atualizada com sucesso.",
        ["plants.toast.registered"]     = "Planta cadastrada com sucesso.",
        ["plants.toast.save_error"]     = "Ocorreu um erro ao salvar a planta.",
        ["plants.toast.deleted"]        = "Planta excluída com sucesso.",
        ["plants.toast.delete_error"]   = "Ocorreu um erro ao excluir a planta.",

        // ── Equipamentos ──────────────────────────────────────────────
        ["equip.register_import"]       = "Cadastro / Importação",
        ["equip.edit"]                  = "Editar Equipamento",
        ["equip.step"]                  = "Passo",
        ["equip.of"]                    = "de",
        ["equip.plant"]                 = "Planta",
        ["equip.select_plant"]          = "-- selecione a planta --",
        ["equip.single_plant_info"]     = "Você tem acesso apenas a esta planta.",
        ["equip.multi_plant_info"]      = "Você tem acesso a",
        ["equip.multi_plant_info2"]     = "plantas.",
        ["equip.operation_mode"]        = "Modo de operação",
        ["equip.manual_mode"]           = "Cadastro manual",
        ["equip.edit_mode_label"]       = "(edição)",
        ["equip.import_mode"]           = "Importação via Excel (modelo LOTOTO)",
        ["equip.header"]                = "Cabeçalho do equipamento",
        ["equip.tag"]                   = "Tag do equipamento",
        ["equip.name"]                  = "Nome / descrição do equipamento",
        ["equip.factory"]               = "Fábrica",
        ["equip.revision"]              = "Data / Revisão",
        ["equip.responsible"]           = "Responsável",
        ["equip.identification"]        = "I. Identificação de energia perigosa",
        ["equip.line_number"]           = "Nº (linha / risco)",
        ["equip.energy_type"]           = "Tipo de energia perigosa / Magnitude",
        ["equip.energy_desc"]           = "Descrição da energia perigosa",
        ["equip.zero_energy"]           = "Verificação de energia zero",
        ["equip.test"]                  = "Teste",
        ["equip.control"]               = "II. Controle de energias perigosas",
        ["equip.isolation_tag"]         = "TAG dispositivo de isolamento",
        ["equip.isolation_location"]    = "Localização dispositivo de isolamento",
        ["equip.isolation_device"]      = "Dispositivo de isolamento",
        ["equip.lockout"]               = "Bloqueio",
        ["equip.images"]                = "Imagens do equipamento",
        ["equip.selected_files"]        = "Arquivos selecionados:",
        ["equip.image_notes"]           = "Notas das imagens",
        ["equip.saving"]                = "Salvando...",
        ["equip.save_changes"]          = "Salvar alterações",
        ["equip.save_equipment"]        = "Salvar equipamento",
        ["equip.select_excel"]          = "Selecione um ou mais arquivos Excel",
        ["equip.view_template"]         = "Ver template",
        ["equip.template_hint"]         = "Utilize o botão \"Ver template\" para conferir a estrutura esperada antes de importar.",
        ["equip.file_col"]              = "Arquivo",
        ["equip.status_col"]            = "Estado",
        ["equip.progress_col"]          = "Progresso",
        ["equip.start_import"]          = "Iniciar importação",
        ["equip.importing"]             = "Importando...",
        ["equip.no_file"]               = "Nenhum arquivo selecionado.",
        ["equip.complete"]              = "Importação/cadastro concluído.",
        ["equip.complete_desc"]         = "A lista de equipamentos foi atualizada na linha abaixo.",
        ["equip.complete_desc2"]        = "Você pode continuar cadastrando manualmente ou importar novos arquivos.",
        ["equip.previous"]              = "Anterior",
        ["equip.next"]                  = "Próximo",
        ["equip.close"]                 = "Fechar",
        ["equip.list_title"]            = "Equipamentos",
        ["equip.search_placeholder"]    = "Tag, nome, energia...",
        ["equip.found"]                 = "equipamento(s) encontrado(s)",
        ["equip.not_found"]             = "Nenhum equipamento encontrado",
        ["equip.col_identification"]    = "I. Identificação",
        ["equip.col_energy_control"]    = "II. Controle energias",
        ["equip.col_active"]            = "Ativo",
        ["equip.col_actions"]           = "Ações",
        ["equip.no_records"]            = "Nenhum equipamento encontrado para a planta selecionada.",
        ["equip.image_unavailable"]     = "Imagem não disponível.",
        ["equip.notes"]                 = "Notas",
        ["equip.no_notes"]              = "Nenhuma nota encontrada para esta imagem.",
        ["equip.delete_confirm_text"]   = "Tem certeza que deseja excluir o equipamento",
        ["equip.view_img_notes"]        = "Ver imagem e notas",
        // Status importação
        ["equip.status.pending"]        = "Pendente",
        ["equip.status.sent"]           = "Enviado",
        ["equip.status.processing"]     = "Processando",
        ["equip.status.completed"]      = "Concluído",
        ["equip.status.error"]          = "Erro",
        // Toasts
        ["equip.toast.saved"]           = "Equipamento salvo com sucesso.",
        ["equip.toast.save_error"]      = "Ocorreu um erro ao salvar o equipamento.",
        ["equip.toast.select_plant"]    = "Selecione uma planta antes de salvar.",
        ["equip.toast.no_permission"]   = "Você não tem permissão para cadastrar equipamentos nesta planta.",
        ["equip.toast.no_perm_import"]  = "Você não tem permissão para importar equipamentos nesta planta.",
        ["equip.toast.no_user"]         = "Usuário não identificado.",
        ["equip.toast.select_advance"]  = "Selecione uma planta antes de avançar.",
        ["equip.toast.no_access"]       = "Você não tem acesso a esta planta.",
        ["equip.toast.select_import"]   = "Selecione uma planta e um arquivo antes de importar.",
        ["equip.toast.deleted"]         = "Equipamento marcado como inativo.",
        ["equip.toast.delete_error"]    = "Erro ao remover o equipamento.",
        ["equip.import.started"]        = "Importação iniciada...",
        ["equip.import.done_prefix"]    = "Importação concluída —",
        ["equip.import.files_ok"]       = "arquivo(s) importado(s) com sucesso.",
        ["equip.import.warnings"]       = "Concluído com avisos —",
        ["equip.import.successes"]      = "sucesso(s),",
        ["equip.import.errors"]         = "erro(s). Verifique os detalhes acima.",
        ["equip.import.failed"]         = "Importação falhou —",
        ["equip.import.failed_desc"]    = "arquivo(s) com erro. Verifique os detalhes acima.",
        ["equip.import.error_table"]    = "arquivo(s) com erro. Verifique os detalhes na tabela.",
        ["equip.import.all_failed"]     = "Todos os arquivos falharam. Verifique os detalhes na tabela.",
        // Template modal
        ["equip.tmpl.title"]            = "Estrutura esperada do arquivo Excel (template LOTOTO)",
        ["equip.tmpl.warning"]          = "O arquivo deve ser <strong>.xlsx</strong> e seguir exactamente esta estrutura. arquivos com colunas em posições diferentes, células vazias obrigatórias ou formato incorrecto serão rejeitados com mensagem de erro detalhada.",
        ["equip.tmpl.cell"]             = "Célula",
        ["equip.tmpl.column"]           = "Coluna",
        ["equip.tmpl.field"]            = "Campo",
        ["equip.tmpl.required"]         = "Obrigatório",
        ["equip.tmpl.observation"]      = "Observação",
        ["equip.tmpl.yes"]              = "Sim",
        ["equip.tmpl.no"]               = "Não",
        ["equip.tmpl.header_section"]   = "Cabeçalho (linha 3)",
        ["equip.tmpl.data_section"]     = "Dados — a partir da linha 7 (arquivo deve ter pelo menos 14 colunas A–N)",
        ["equip.tmpl.group1"]           = "Grupo I — Identificação de energia perigosa",
        ["equip.tmpl.group2"]           = "Grupo II — Controle de energias perigosas",
        ["equip.tmpl.visual_map"]       = "Mapa visual das colunas (linha de dados)",
        ["equip.tmpl.special_rules"]    = "Regras especiais",
        ["equip.tmpl.required_badge"]   = "⭐ Obrigatório",
        ["equip.tmpl.col_b_note"]       = "Coluna B (N°) deve conter um número inteiro positivo em cada linha de risco.",
        ["equip.tmpl.letter"]           = "Letra",
        // Cabeçalho table rows
        ["equip.tmpl.tag_field"]        = "Tag do equipamento",
        ["equip.tmpl.tag_obs"]          = "Identificador único do equipamento",
        ["equip.tmpl.name_field"]       = "Nome / descrição do equipamento",
        ["equip.tmpl.name_obs"]         = "Nome descritivo do equipamento",
        ["equip.tmpl.factory_field"]    = "Fábrica / Planta",
        ["equip.tmpl.factory_obs"]      = "Nome da fábrica ou planta",
        ["equip.tmpl.revision_field"]   = "Revisão / Data",
        ["equip.tmpl.revision_obs"]     = "Informação de revisão ou data do documento",
        // Grupo I rows
        ["equip.tmpl.g1_number_field"]  = "N° (número da linha)",
        ["equip.tmpl.g1_number_obs"]    = "Inteiro positivo. Identifica cada linha de risco. Linhas sem número são ignoradas. Linhas com célula A mesclada até X/Y/Z/XFD são tratadas como comentários.",
        ["equip.tmpl.g1_type_field"]    = "Tipo de energia / Magnitude",
        ["equip.tmpl.g1_type_obs"]      = "Ex: Elétrica, Pneumática, Hidráulica…",
        ["equip.tmpl.g1_desc_field"]    = "Descrição da energia perigosa",
        ["equip.tmpl.g1_desc_obs"]      = "Texto livre descrevendo o risco",
        ["equip.tmpl.g1_image_field"]   = "Foto / imagem",
        ["equip.tmpl.g1_image_obs"]     = "Imagem in-cell ou imagem flutuante nas colunas E–H. Múltiplas imagens na mesma linha são mescladas verticalmente.",
        // Grupo II rows
        ["equip.tmpl.g2_iso_tag_field"] = "TAG dispositivo de isolamento",
        ["equip.tmpl.g2_iso_tag_obs"]   = "Código/TAG do dispositivo",
        ["equip.tmpl.g2_loc_field"]     = "Localização do dispositivo",
        ["equip.tmpl.g2_loc_obs"]       = "Localização física do dispositivo",
        ["equip.tmpl.g2_device_field"]  = "Dispositivo de isolamento",
        ["equip.tmpl.g2_device_obs"]    = "Descrição do dispositivo de isolamento",
        ["equip.tmpl.g2_lockout_field"] = "Bloqueio",
        ["equip.tmpl.g2_lockout_obs"]   = "Tipo de bloqueio aplicado",
        ["equip.tmpl.g2_zero_field"]    = "Verificação de energia zero",
        ["equip.tmpl.g2_zero_obs"]      = "Método de verificação de energia zero",
        ["equip.tmpl.g2_test_field"]    = "Teste",
        ["equip.tmpl.g2_test_obs"]      = "Procedimento de teste",
        // Visual map
        ["equip.tmpl.map_number"]       = "N°",
        ["equip.tmpl.map_energy_type"]  = "Tipo energia",
        ["equip.tmpl.map_desc"]         = "Descrição",
        ["equip.tmpl.map_photo"]        = "Foto",
        ["equip.tmpl.map_float_zone"]   = "Zona imagens flutuantes (E–H)",
        ["equip.tmpl.map_iso_tag"]      = "TAG disp.",
        ["equip.tmpl.map_location"]     = "Localiz.",
        ["equip.tmpl.map_device"]       = "Dispositivo",
        ["equip.tmpl.map_lockout"]      = "Bloqueio",
        ["equip.tmpl.map_zero"]         = "Energ. zero",
        ["equip.tmpl.map_test"]         = "Teste",
        // Special rules
        ["equip.tmpl.rule_comments"]       = "Linhas de comentário:",
        ["equip.tmpl.rule_comments_desc"]  = "Linhas onde a célula A está mesclada até colunas X, Y, Z ou XFD são ignoradas durante o parse.",
        ["equip.tmpl.rule_floating"]       = "Imagens flutuantes:",
        ["equip.tmpl.rule_floating_desc"]  = "Imagens sobre as colunas E–H associadas à linha de risco são extraídas automaticamente. Múltiplas imagens na mesma linha são mescladas verticalmente.",
        ["equip.tmpl.rule_balloons"]       = "Balões de nota (shapes):",
        ["equip.tmpl.rule_balloons_desc"]  = "Shapes com texto nas colunas E–H são extraídos como notas da imagem.",
        ["equip.tmpl.rule_min_cols"]       = "Colunas mínimas:",
        ["equip.tmpl.rule_min_cols_desc"]  = "O arquivo deve ter pelo menos 14 colunas (A–N).",
        ["equip.tmpl.rule_data_start"]     = "Início dos dados:",
        ["equip.tmpl.rule_data_start_desc"]= "Os dados começam na linha 7. As linhas 1–6 são reservadas ao cabeçalho do template.",
        ["equip.tmpl.rule_stop"]           = "Paragem automática:",
        ["equip.tmpl.rule_stop_desc"]      = "O parse para após 10 linhas consecutivas sem número na coluna B.",

        // ── PLE ────────────────────────────────────────────────────────
        ["nav.ple"]                  = "Bloqueio",
        ["ple.title"]                = "Bloqueio de Energia",
        ["ple.new"]                  = "Novo Bloqueio",
        ["ple.edit"]                 = "Editar Bloqueio",
        ["ple.list"]                 = "Lista de Bloqueios",
        ["ple.number"]               = "Número",
        ["ple.equipment"]            = "Equipamento",
        ["ple.tag_disp"]             = "TAG Disp.",
        ["ple.department"]           = "Departamento",
        ["ple.operation"]            = "Operação",
        ["ple.description"]          = "Descrição",
        ["ple.start_date"]           = "Data Início",
        ["ple.end_date"]             = "Data Fim",
        ["ple.status"]               = "Status",
        ["ple.observations"]         = "Observações",
        ["ple.created_by"]           = "Criado por",
        ["ple.modified_by"]          = "Modificado por",
        ["ple.finalized_by"]         = "Finalizado por",
        ["ple.created_at"]           = "Data Criação",
        ["ple.plant"]                = "Planta",
        ["ple.select_equipment"]     = "Selecione o equipamento...",
        ["ple.select_plant"]         = "Selecione a planta...",

        // Status
        ["ple.status.criado"]        = "Criado",
        ["ple.status.em_andamento"]  = "Em Andamento",
        ["ple.status.cancelado"]      = "Cancelado",
        ["ple.status.inicio_desbloqueio"] = "Início do Desbloqueio",
        ["ple.status.finalizado"]    = "Finalizado",

        // Nota de estado exibida na faixa-sinal do detalhe do PLE. Descritiva:
        // relata a situação física, sem emitir instrução de segurança.
        ["nav.panel"]                = "Painel",
        // Painel de alertas / mural de TV
        ["mural.panel_title"]        = "Painel de Bloqueio/Desbloqueio",
        ["mural.state_blocked"]      = "Bloqueado",
        ["mural.state_process"]      = "Em processo",
        ["mural.state_free"]         = "Livre",
        ["mural.no_equipment"]       = "Nenhum equipamento cadastrado para esta planta.",
        ["mural.none_blocked"]       = "Nenhum equipamento bloqueado no momento.",
        ["mural.auto_refresh"]       = "Atualização automática a cada {0} min",
        ["mural.updated_at"]         = "Atualizado às {0}",
        ["mural.plant_not_found"]    = "Planta não encontrada",
        ["mural.loading"]            = "Carregando...",
        ["mural.select_plant"]       = "Selecione uma planta para visualizar o painel.",
        ["mural.refresh"]            = "Atualizar",
        ["mural.open_tv"]            = "Abrir versão para TV (tela cheia)",
        ["mural.tv"]                 = "TV",
        ["mural.leaders"]            = "Líder(es) de bloqueio",
        ["mural.requests"]           = "Requisição(ões)",

        ["ple.none_found"]                     = "Nenhum PLE encontrado.",
        ["ple.legend"]                         = "Legenda",
        ["ple.state_note.criado"]              = "Bloqueio ainda não iniciado.",
        ["ple.state_note.em_andamento"]        = "Energia isolada — bloqueio ativo.",
        ["ple.state_note.cancelado"]           = "PLE cancelado.",
        ["ple.state_note.inicio_desbloqueio"]  = "Desbloqueio iniciado.",
        ["ple.state_note.finalizado"]          = "Bloqueio encerrado.",

        // Wizard steps
        ["ple.step1"]                = "Identificação",
        ["ple.step2"]                = "Avaliação de Riscos",
        ["ple.step3"]                = "Revisão e Confirmação",
        ["ple.step_of"]              = "de",

        // Itens (Avaliação de Risco)
        ["ple.item.task"]            = "Tarefa",
        ["ple.item.hazard"]          = "Perigo",
        ["ple.item.exposed"]         = "Nº Expostos",
        ["ple.item.severity_before"] = "Gravidade (antes)",
        ["ple.item.probability_before"] = "Probabilidade (antes)",
        ["ple.item.risk_before"]     = "Nível Risco (antes)",
        ["ple.item.measures"]        = "Medidas de Proteção",
        ["ple.item.severity_after"]  = "Gravidade (após)",
        ["ple.item.probability_after"] = "Probabilidade (após)",
        ["ple.item.risk_after"]      = "Nível Risco (após)",
        ["ple.item.add"]             = "Adicionar Item",
        ["ple.item.remove"]          = "Remover",
        ["ple.item.before_reduction"]  = "Antes da Redução de Riscos",
        ["ple.item.after_reduction"]   = "Após a Redução do Risco",

        // Severidade / Probabilidade / Risco
        ["ple.severity.catastrophic"] = "Catastrófico",
        ["ple.severity.serious"]      = "Grave",
        ["ple.severity.moderate"]     = "Moderado",
        ["ple.severity.minor"]        = "Menor",
        ["ple.probability.very_likely"] = "Muito provável",
        ["ple.probability.likely"]      = "Provável",
        ["ple.probability.unlikely"]    = "Improvável",
        ["ple.probability.remote"]      = "Remoto",
        ["ple.risk.high"]              = "Alto",
        ["ple.risk.medium"]            = "Médio",
        ["ple.risk.low"]               = "Baixo",
        ["ple.risk.insignificant"]     = "Insignificante",

        // Ações
        ["ple.action.start"]         = "Iniciar",
        ["ple.action.suspend"]       = "Suspender",
        ["ple.action.cancel_ple"]    = "Cancelar Bloqueio",
        ["ple.cancel_reason"]        = "Motivo do Cancelamento",
        ["ple.action.resume"]        = "Retomar",
        ["ple.action.finalize"]      = "Finalizar",
        ["ple.action.start_unlock"]  = "Início do Desbloqueio",
        ["ple.confirm_start_unlock"] = "Tem certeza que deseja iniciar o desbloqueio? O Comando Central será o responsável pela finalização.",
        ["ple.action.delete"]        = "Excluir",
        ["ple.action.print"]         = "Imprimir",
        ["ple.action.save"]          = "Salvar",
        ["ple.action.cancel"]        = "Cancelar",
        ["ple.action.next"]          = "Próximo",
        ["ple.action.previous"]      = "Anterior",
        ["ple.action.confirm"]       = "Confirmar",

        // Suspensão
        ["ple.suspend_reason"]       = "Motivo da Suspensão",
        ["ple.suspend_reason_required"] = "Informe o motivo da suspensão",

        // Histórico
        ["ple.history"]              = "Histórico",
        ["ple.history.action"]       = "Ação",
        ["ple.history.user"]         = "Usuário",
        ["ple.history.date"]         = "Data/Hora",
        ["ple.history.details"]      = "Detalhes",
        ["ple.history.status_from"]  = "De",
        ["ple.history.status_to"]    = "Para",

        // Toasts
        ["ple.toast.created"]        = "Bloqueio criado com sucesso!",
        ["ple.toast.updated"]        = "Bloqueio atualizado com sucesso!",
        ["ple.toast.deleted"]        = "Bloqueio excluído com sucesso!",
        ["ple.toast.status_changed"] = "Status do bloqueio alterado com sucesso!",
        ["ple.toast.error"]          = "Erro ao processar o bloqueio.",
        ["ple.toast.cannot_edit"]    = "Não é possível editar um bloqueio finalizado.",

        // Filtros
        ["ple.filter.all_status"]    = "Todos os status",
        ["ple.filter.search"]        = "Buscar por número, equipamento, departamento...",

        // Confirmação
        ["ple.confirm_delete"]       = "Tem certeza que deseja excluir este bloqueio?",
        ["ple.confirm_finalize"]     = "Tem certeza que deseja finalizar este bloqueio? Após finalizado, não poderá ser editado.",

        // Impressão
        ["ple.print.title"]          = "Procedimento de Liberação de Energia",
        ["ple.print.copy"]           = "Via",
        ["ple.print.copy1"]          = "1ª Via - Controle",
        ["ple.print.copy2"]          = "2ª Via - Campo",

        // Indicador de manutenção
        ["ple.maintenance_badge"]    = "Em processo de bloqueio",
        ["ple.maintenance_badge_active"] = "Bloqueio Ativo",
        ["ple.users_with_permission"] = "Usuários com permissão",
        ["ple.users_with_permission_hint"] = "(opcional — mesmos poderes que o criador)",
        ["ple.authorized_users"]      = "Usuários autorizados",

        // ── Avaliação de Risco ─────────────────────────────────────────
        ["nav.risk_assessment"]       = "Avaliação de Risco",
        ["ar.title"]                  = "Avaliação de Risco — Método Alternativo",
        ["ar.new"]                    = "Nova Avaliação",
        ["ar.edit"]                   = "Editar Avaliação",
        ["ar.list"]                   = "Avaliações de Risco",
        ["ar.none_found"]             = "Nenhuma avaliação encontrada.",
        ["ar.number"]                 = "Número",
        ["ar.department"]             = "Departamento",
        ["ar.operation"]              = "Operação",
        ["ar.task"]                   = "Tarefa / Descrição",
        ["ar.date"]                   = "Data",
        ["ar.observations"]           = "Observações",
        ["ar.status"]                 = "Status",
        ["ar.status.ativa"]        = "Ativa",
        ["ar.status.inativa"]       = "Inativa",
        ["ar.plant"]                  = "Planta",
        ["ar.select_plant"]           = "Selecione a planta...",
        ["ar.created_by"]             = "Criado por",
        ["ar.step1"]                  = "Identificação",
        ["ar.step2"]                  = "Avaliação de Riscos",
        ["ar.step3"]                  = "Revisão",
        ["ar.item.task"]              = "Tarefa",
        ["ar.item.hazard"]            = "Perigo",
        ["ar.item.exposed"]           = "Nº Expostos",
        ["ar.item.severity_before"]   = "Gravidade (antes)",
        ["ar.item.probability_before"]= "Probabilidade (antes)",
        ["ar.item.risk_before"]       = "Nível Risco (antes)",
        ["ar.item.measures"]          = "Medidas de Proteção",
        ["ar.item.severity_after"]    = "Gravidade (após)",
        ["ar.item.probability_after"] = "Probabilidade (após)",
        ["ar.item.risk_after"]        = "Nível Risco (após)",
        ["ar.item.add"]               = "Adicionar Item",
        ["ar.item.remove"]            = "Remover",
        ["ar.item.before_reduction"]  = "Antes da Redução de Riscos",
        ["ar.item.after_reduction"]   = "Após a Redução do Risco",
        ["ar.action.save"]            = "Salvar",
        ["ar.action.cancel"]          = "Cancelar",
        ["ar.action.conclude"]        = "Concluir",
        ["ar.action.print"]           = "Imprimir",
        ["ar.action.delete"]          = "Excluir",
        ["ar.action.next"]            = "Próximo",
        ["ar.action.previous"]        = "Anterior",
        ["ar.action.deactivate"]      = "Inativar",
        ["ar.action.activate"]        = "Ativar",
        ["ar.confirm_deactivate"]     = "Inativar esta avaliação?",
        ["ar.deactivate_title"]       = "Inativar",
        ["ar.toast.created"]          = "Avaliação criada com sucesso!",
        ["ar.toast.updated"]          = "Avaliação atualizada com sucesso!",
        ["ar.toast.concluded"]        = "Avaliação concluída!",
        ["ar.toast.deleted"]          = "Avaliação excluída!",
        ["ar.toast.error"]            = "Erro ao processar avaliação.",
        ["ar.toast.status_changed"]   = "Status da avaliação alterado com sucesso!",
        ["ar.confirm_conclude"]       = "Concluir esta avaliação? Após concluída, não poderá ser editada.",
        ["ar.confirm_delete"]         = "Excluir esta avaliação?",
        ["ar.filter.all_status"]      = "Todos os status",
        ["ar.filter.search"]          = "Buscar por número, departamento, tarefa...",

        // ── Auditoria (#5b) ───────────────────────────────────────────
        ["audit.title"]               = "Auditoria",
        ["audit.subtitle"]            = "Trilha de alterações do sistema",
        ["audit.filter.period_from"]  = "De",
        ["audit.filter.period_to"]    = "Até",
        ["audit.filter.user"]         = "Usuário executor",
        ["audit.filter.entity"]       = "Entidade",
        ["audit.filter.action"]       = "Ação",
        ["audit.filter.all_users"]    = "Todos",
        ["audit.filter.all_entities"] = "Todas",
        ["audit.filter.all_actions"]  = "Todas",
        ["audit.filter.apply"]        = "Filtrar",
        ["audit.filter.clear"]        = "Limpar",
        ["audit.col_when"]            = "Quando",
        ["audit.col_user"]            = "Usuário",
        ["audit.col_entity"]          = "Entidade",
        ["audit.col_key"]             = "Registro",
        ["audit.col_action"]          = "Ação",
        ["audit.col_details"]         = "Detalhes",
        ["audit.action_create"]       = "Criar",
        ["audit.action_update"]       = "Atualizar",
        ["audit.action_delete"]       = "Excluir",
        ["audit.no_results"]          = "Nenhuma entrada encontrada para os filtros informados.",
        ["audit.search_placeholder"]  = "Buscar por usuário, chave ou ação...",
        ["audit.diff_title"]          = "Alteração — antes e depois",
        ["audit.diff_field"]          = "Campo",
        ["audit.diff_before"]         = "Antes",
        ["audit.diff_after"]          = "Depois",
        ["audit.unknown_user"]        = "—",

        // ── Relatório de Usuários (#6a) ───────────────────────────────
        ["report.users.title"]        = "Relatório de Usuários",
        ["report.users.subtitle"]     = "Usuários ativos consolidados",
        ["report.users.filter.plant"] = "Planta",
        ["report.users.filter.profile"] = "Perfil",
        ["report.users.filter.bond"]  = "Vínculo",
        ["report.users.filter.status"] = "Status de validade",
        ["report.users.filter.all"]   = "Todos",
        ["report.users.status_active"] = "Vigente",
        ["report.users.status_expiring"] = "Vencendo (≤30d)",
        ["report.users.status_expired"] = "Vencido",
        ["report.users.export_excel"] = "Exportar Excel",
        ["report.users.export_pdf"]   = "Exportar PDF",
        ["report.users.col_user"]     = "Usuário",
        ["report.users.col_profiles"] = "Perfis",
        ["report.users.col_plants"]   = "Plantas",
        ["report.users.col_bond"]     = "Vínculo",
        ["report.users.col_validity"] = "Validade do acesso",
        ["report.users.col_training"] = "Treinamento",
        ["report.users.col_last_login"] = "Último login",
        ["report.users.col_responsibles"] = "Responsáveis",
        ["report.users.created_by_short"] = "Criado por",
        ["report.users.updated_by_short"] = "Alterado por",
        ["report.users.no_results"]   = "Nenhum usuário encontrado para os filtros informados.",
        ["report.users.search_placeholder"] = "Nome, login, planta ou empresa...",
        ["report.users.not_required"] = "Não exigido",

        // ── Campanha de Revalidação (#6b) ─────────────────────────────
        ["campaign.title"]            = "Revalidação",
        ["campaign.subtitle"]         = "Revisão periódica dos acessos",
        ["campaign.new"]              = "Nova",
        ["campaign.name"]             = "Nome",
        ["campaign.plants"]           = "Plantas",
        ["campaign.due_date"]         = "Conclusão prevista",
        ["campaign.periodicity"]      = "Periodicidade",
        ["campaign.periodicity_monthly"] = "Mensal",
        ["campaign.periodicity_quarterly"] = "Trimestral",
        ["campaign.periodicity_biannual"] = "Semestral",
        ["campaign.periodicity_yearly"] = "Anual",
        ["campaign.status"]           = "Status",
        ["campaign.status_planned"]   = "Planejada",
        ["campaign.status_running"]   = "Em andamento",
        ["campaign.status_completed"] = "Concluída",
        ["campaign.status_cancelled"] = "Cancelada",
        ["campaign.start"]            = "Início",
        ["campaign.end_expected"]     = "Conclusão prevista",
        ["campaign.end_actual"]       = "Conclusão",
        ["campaign.progress"]         = "Progresso",
        ["campaign.created_by"]       = "Criada por",
        ["campaign.notes"]            = "Notas",
        ["campaign.no_results"]       = "Nenhuma campanha cadastrada.",
        ["campaign.create_button"]    = "Criar",
        ["campaign.detail_title"]     = "Revisão dos acessos",
        ["campaign.col_user"]         = "Usuário",
        ["campaign.col_snapshot"]     = "Situação no início da campanha",
        ["campaign.col_decision"]     = "Decisão",
        ["campaign.col_who"]          = "Decidido por",
        ["campaign.col_when"]         = "Quando",
        ["campaign.col_note"]         = "Observação",
        ["campaign.decision_keep"]    = "Manter",
        ["campaign.decision_adjust"]  = "Ajustar",
        ["campaign.decision_revoke"]  = "Revogar (inativar)",
        ["campaign.decision_pending"] = "Pendente",
        ["campaign.filter.user"]      = "Usuário",
        ["campaign.filter.decision"]  = "Decisão",
        ["campaign.filter.all"]       = "Todas",
        ["campaign.filter.search_placeholder"] = "Nome, login ou resumo...",
        ["campaign.save_decision"]    = "Salvar",
        ["campaign.complete"]         = "Concluir",
        ["campaign.cancel"]           = "Cancelar",
        ["campaign.cancel_yes"]       = "Sim, cancelar",
        ["campaign.cancel_confirm"]   = "Cancelar esta campanha?",
        ["campaign.toast.created"]    = "Campanha criada e gestores notificados.",
        ["campaign.toast.decided"]    = "Decisão registrada.",
        ["campaign.toast.completed"]  = "Campanha concluída.",
        ["campaign.toast.cancelled"]  = "Campanha cancelada.",
        ["campaign.toast.name_required"] = "Informe o nome da campanha.",
        ["campaign.toast.plants_required"] = "Selecione ao menos uma planta.",
        ["campaign.toast.due_required"] = "Informe a data de conclusão prevista.",
    };

    // ──────────────────────────────────────────────────────────────────
    //  ENGLISH (en-US)
    // ──────────────────────────────────────────────────────────────────
    private static readonly Dictionary<string, string> _en = new()
    {
        // ── Navigation ────────────────────────────────────────────────
        ["nav.search"]           = "Search",
        ["nav.equipments"]       = "Equipment",
        ["nav.users"]            = "Users",
        ["nav.plants"]           = "Plants",
        ["nav.logout"]           = "Logout",
        ["nav.restricted_admin"] = "Restricted to administrator",
        ["nav.restricted_super"] = "Restricted to Super Manager",
        ["nav.no_plant"]         = "No plant",
        ["nav.plant_label"]      = "Plant",
        ["nav.date"]             = "Date",
        ["nav.operator"]         = "Operator",
        ["nav.environment"]      = "Environment",
        ["nav.sections"]         = "Sections",
        ["nav.audit"]            = "Audit",
        ["nav.reports"]          = "Reports",
        ["nav.campaigns"]        = "Campaigns",

        // ── Login ─────────────────────────────────────────────────────
        ["login.login"]          = "Login",
        ["login.password"]       = "Password",
        ["login.plant"]          = "Plant",
        ["login.select"]         = "Select...",
        ["login.enter"]          = "Sign In",
        ["login.signing_in"]     = "Signing in...",
        ["login.direct_access"]  = "Direct access",
        ["login.field_blocked"]  = "Field blocked for this user",
        ["login.auth_error"]     = "Could not authenticate. Check the data and try again.",
        // Bond / access validity (#2)
        ["login.access_expired"] = "Your access has expired. Contact the plant's Workplace Safety team to renew.",
        ["login.access_expiring_today"] = "Your access expires today. Contact Workplace Safety to renew.",
        ["login.access_expiring_in_days"] = "Your access expires in {0} day(s). Contact Workplace Safety to renew.",
        // Training (#3)
        ["login.training_expired"] = "Your LOTOTO training has expired. Contact the plant's Workplace Safety team to renew.",
        ["login.training_expiring_today"] = "Your LOTOTO training expires today. Contact Workplace Safety to renew.",
        ["login.training_expiring_in_days"] = "Your LOTOTO training expires in {0} day(s). Contact Workplace Safety to renew.",
        ["login.continue"]       = "Continue",

        // ── Environment ───────────────────────────────────────────────
        ["env.homologacao"]      = "Staging Environment",

        // ── Common ────────────────────────────────────────────────────
        ["common.save"]          = "Save changes",
        ["common.register"]      = "Register",
        ["common.delete"]        = "Delete",
        ["common.edit"]          = "Edit",
        ["common.close"]         = "Close",
        ["common.view"]          = "View",
        ["common.yes_delete"]    = "Yes, delete",
        ["common.no"]            = "No",
        ["common.confirm_delete"]= "Confirm deletion",
        ["common.success"]       = "Success",
        ["common.error"]         = "Error",
        ["common.attention"]     = "Attention",
        ["common.page"]          = "Page",
        ["common.of"]            = "of",
        ["common.active"]        = "Active",
        ["common.inactive"]      = "Inactive",
        ["common.active_f"]      = "Active",
        ["common.inactive_f"]    = "Inactive",
        ["common.actions"]       = "Actions",
        ["common.search"]        = "Search",
        ["common.loading"]       = "Loading...",
        ["common.processing"]    = "Processing...",
        ["common.clear"]         = "Clear",
        ["common.cancel_edit"]   = "Cancel edit",
        ["common.select_state"]  = "-- select state --",
        ["common.cancel_edit_title"] = "Cancel edit",
        ["common.confirm"]       = "Confirm",
        ["common.select_all"]    = "Select all",
        // Timeline (History) – action labels
        ["timeline.action.created"]     = "Created",
        ["timeline.action.started"]     = "Started",
        ["timeline.action.cancelled"]   = "Cancelled",
        ["timeline.action.start_unlock"] = "Unlock Start",
        ["timeline.action.finalized"]   = "Finalized",
        ["timeline.action.modified"]    = "Modified",
        ["timeline.action.deleted"]     = "Deleted",
        ["timeline.action.deactivated"] = "Deactivated",
        ["timeline.action.activated"]   = "Activated",

        // ── Home ──────────────────────────────────────────────────────
        ["home.title"]                  = "Hazardous energies query by equipment",
        ["home.filters"]                = "Search filters",
        ["home.plant"]                  = "Plant",
        ["home.select_plant"]           = "Select...",
        ["home.all_my_plants"]          = "All my plants",
        ["home.tag"]                    = "Equipment tag",
        ["home.tag_placeholder"]        = "Ex.: FMTZ-100-BC11",
        ["home.name_desc"]              = "Equipment name / description",
        ["home.name_placeholder"]       = "Part of name...",
        ["home.energy_type"]            = "Energy type",
        ["home.energy_type_placeholder"]= "Ex.: Electrical, Pneumatic...",
        ["home.energy_desc"]            = "Hazardous energy description",
        ["home.energy_desc_placeholder"]= "Part of description...",
        ["home.isolation_tag"]          = "Isolation device TAG",
        ["home.isolation_tag_ph"]       = "Device TAG",
        ["home.device_location"]        = "Device location",
        ["home.device_location_ph"]     = "Panel, area, room...",
        ["home.isolation_device"]       = "Isolation device",
        ["home.isolation_device_ph"]    = "Circuit breaker, valve, etc.",
        ["home.lockout"]                = "Lockout",
        ["home.lockout_ph"]             = "Lockout type",
        ["home.zero_energy"]            = "Zero energy verification",
        ["home.zero_energy_ph"]         = "Part of verification text...",
        ["home.test"]                   = "Test",
        ["home.test_ph"]                = "Part of test text...",
        ["home.results"]                = "Results",
        ["home.equipment_found"]        = "equipment found",
        ["home.not_found_filter"]       = "No equipment found for filters",
        ["home.loading"]                = "Loading equipment...",
        ["home.searching"]              = "Searching...",
        ["home.no_records"]             = "No records for the specified filters.",
        ["home.view_image"]             = "View image",
        ["home.image_unavailable"]      = "Image not available.",
        ["home.notes"]                  = "Notes",
        ["home.no_notes"]               = "No notes found for this image.",
        ["home.table.identification"]   = "I. Identification",
        ["home.table.energy_control"]   = "II. Energy control",
        ["home.table.tag"]              = "Tag",
        ["home.table.equipment"]        = "Equip.",
        ["home.table.number"]           = "No.",
        ["home.table.energy_type"]      = "Energy type",
        ["home.table.img"]              = "Img",
        ["home.table.energy_desc"]      = "Energy desc.",
        ["home.table.isolation_tag"]    = "Dev. TAG",
        ["home.table.loc_device"]       = "Dev. loc.",
        ["home.table.device"]           = "Dev.",
        ["home.table.lockout"]          = "Lock.",
        ["home.table.zero_energy"]      = "Zero energy verif.",
        ["home.table.test"]             = "Test",
        ["home.table.plant"]            = "Plant",
        // Toasts
        ["home.toast.select_plant"]     = "Select a plant to search equipment.",
        ["home.toast.no_plant_claim"]   = "Plant not found in user claims.",
        ["home.toast.load_error"]       = "Error loading equipment.",

        // ── Users ─────────────────────────────────────────────────────
        ["users.register"]              = "Register User",
        ["users.edit"]                  = "Edit User",
        ["users.login_field"]           = "Login",
        ["users.full_name"]             = "Full name",
        ["users.password"]              = "Password",
        ["users.password_hint"]         = "Leave blank to keep current password.",
        ["users.access_profile"]        = "Access profile",
        ["users.access_profiles"]       = "Access profiles (select one or more)",
        ["users.profile_super_exclusive"] = "Super Manager cannot be combined with other profiles.",
        // Bond Employee/Contractor (#2)
        ["users.bond_type"]             = "Bond type",
        ["users.bond_employee"]         = "Employee",
        ["users.bond_contractor"]       = "Partner",
        ["users.company_name"]          = "Partner company",
        ["users.access_validity"]       = "Access validity",
        ["users.access_validity_hint"]  = "Maximum of 6 months from today.",
        ["users.col_bond"]              = "Bond",
        ["users.col_validity"]          = "Validity",
        ["users.validity_expired"]      = "Expired",
        ["users.validity_expiring"]     = "Expiring (≤30d)",
        ["users.validity_active"]       = "Active",
        ["users.toast.company_required"] = "For Partner, enter the company name.",
        ["users.toast.validity_required"] = "For Partner, enter the access validity date.",
        ["users.toast.validity_max_6m"] = "Access validity cannot exceed 6 months.",
        // Users page sub-tabs toolbox (#4)
        ["users.tab.registration"]      = "Registration",
        ["users.tab.revalidation"]      = "Revalidation",
        ["users.tab.audit"]             = "Audit",
        ["users.tab.reports"]           = "Reports",
        ["users.plants_select"]         = "Plants (select one or more)",
        ["users.admin_restriction"]     = "As administrator, you can only assign users to your plants",
        ["users.select_plant_required"] = "Select at least one plant",
        ["users.active"]                = "Active user",
        ["users.search"]                = "User Search",
        ["users.search_placeholder"]    = "Login, name, profile, bond, company or plant...",
        ["users.found"]                 = "user(s) found",
        ["users.not_found"]             = "No users found",
        ["users.col_login"]             = "Login",
        ["users.col_name"]              = "Name",
        ["users.col_profile"]           = "Profile",
        ["users.col_profiles"]          = "Profiles",
        ["users.col_plants"]            = "Plants",
        ["users.col_active"]            = "Active",
        ["users.all_plants"]            = "All plants",
        ["users.no_plant"]              = "No plant",
        ["users.no_records"]            = "No users found for the specified filters.",
        ["users.delete_confirm_text"]   = "Are you sure you want to delete user",
        ["users.profile_user"]          = "User",
        ["users.profile_admin"]         = "Administrator",
        ["users.profile_super"]         = "Super Manager",
        ["users.profile_final"]         = "Lockout Leader",
        ["users.profile_central"]       = "Central Command",
        ["users.training_completed"]    = "LOTOTO training completed",
        // Training validity (#3)
        ["users.training_validity"]     = "Training validity",
        ["users.training_validity_hint"] = "Auto-filled: training date + 2 years.",
        ["users.col_training"]          = "Training",
        ["users.training_not_required"] = "Not required for this profile",
        // Toasts
        ["users.toast.login_required"]  = "Login is required.",
        ["users.toast.only_super"]      = "Only Super Managers can register Super Managers.",
        ["users.toast.profile_required"] = "Select at least one profile.",
        ["users.toast.profile_super_exclusive"] = "Super Manager cannot be combined with other profiles.",
        ["users.toast.select_plant"]    = "Select at least one plant.",
        ["users.toast.own_plants_only"] = "You can only assign users to your own plants.",
        ["users.toast.duplicate"]       = "A user with this login already exists for one of the selected plants.",
        ["users.toast.no_permission"]   = "You don't have permission to edit this user.",
        ["users.toast.saved"]           = "User updated successfully.",
        ["users.toast.registered"]      = "User registered successfully.",
        ["users.toast.save_error"]      = "Error saving user.",
        ["users.toast.deleted"]         = "User deleted successfully.",
        ["users.toast.delete_error"]    = "Error deleting user.",
        // Audit trail (#1c)
        ["users.audit_title"]           = "Registration audit",
        ["users.created_by"]            = "Created by",
        ["users.updated_by"]            = "Updated by",
        ["users.audit_at"]              = "at",
        ["users.audit_unknown"]         = "—",

        // ── Plants ────────────────────────────────────────────────────
        ["plants.register"]             = "Register Plant",
        ["plants.edit"]                 = "Edit Plant",
        ["plants.name"]                 = "Plant Name",
        ["plants.code"]                 = "Code",
        ["plants.location"]             = "Location",
        ["plants.active"]               = "Active plant",
        ["plants.search"]               = "Plant Search",
        ["plants.search_placeholder"]   = "Name, code or location...",
        ["plants.found"]                = "plant(s) found",
        ["plants.not_found"]            = "No plants found",
        ["plants.col_code"]             = "Code",
        ["plants.col_name"]             = "Name",
        ["plants.col_location"]         = "Location",
        ["plants.col_active"]           = "Active",
        ["plants.active_badge"]         = "Active",
        ["plants.inactive_badge"]       = "Inactive",
        ["plants.no_records"]           = "No plants found for the specified filters.",
        ["plants.delete_confirm_text"]  = "Are you sure you want to delete",
        // Toasts
        ["plants.toast.saved"]          = "Plant updated successfully.",
        ["plants.toast.registered"]     = "Plant registered successfully.",
        ["plants.toast.save_error"]     = "An error occurred while saving the plant.",
        ["plants.toast.deleted"]        = "Plant deleted successfully.",
        ["plants.toast.delete_error"]   = "An error occurred while deleting the plant.",

        // ── Equipment ─────────────────────────────────────────────────
        ["equip.register_import"]       = "Registration / Import",
        ["equip.edit"]                  = "Edit Equipment",
        ["equip.step"]                  = "Step",
        ["equip.of"]                    = "of",
        ["equip.plant"]                 = "Plant",
        ["equip.select_plant"]          = "-- select plant --",
        ["equip.single_plant_info"]     = "You only have access to this plant.",
        ["equip.multi_plant_info"]      = "You have access to",
        ["equip.multi_plant_info2"]     = "plants.",
        ["equip.operation_mode"]        = "Operation mode",
        ["equip.manual_mode"]           = "Manual registration",
        ["equip.edit_mode_label"]       = "(editing)",
        ["equip.import_mode"]           = "Import via Excel (LOTOTO template)",
        ["equip.header"]                = "Equipment header",
        ["equip.tag"]                   = "Equipment tag",
        ["equip.name"]                  = "Equipment name / description",
        ["equip.factory"]               = "Factory",
        ["equip.revision"]              = "Date / Revision",
        ["equip.responsible"]           = "Responsible",
        ["equip.identification"]        = "I. Hazardous energy identification",
        ["equip.line_number"]           = "No. (line / risk)",
        ["equip.energy_type"]           = "Hazardous energy type / Magnitude",
        ["equip.energy_desc"]           = "Hazardous energy description",
        ["equip.zero_energy"]           = "Zero energy verification",
        ["equip.test"]                  = "Test",
        ["equip.control"]               = "II. Hazardous energy control",
        ["equip.isolation_tag"]         = "Isolation device TAG",
        ["equip.isolation_location"]    = "Isolation device location",
        ["equip.isolation_device"]      = "Isolation device",
        ["equip.lockout"]               = "Lockout",
        ["equip.images"]                = "Equipment images",
        ["equip.selected_files"]        = "Selected files:",
        ["equip.image_notes"]           = "Image notes",
        ["equip.saving"]                = "Saving...",
        ["equip.save_changes"]          = "Save changes",
        ["equip.save_equipment"]        = "Save equipment",
        ["equip.select_excel"]          = "Select one or more Excel files",
        ["equip.view_template"]         = "View template",
        ["equip.template_hint"]         = "Use the \"View template\" button to check the expected structure before importing.",
        ["equip.file_col"]              = "File",
        ["equip.status_col"]            = "Status",
        ["equip.progress_col"]          = "Progress",
        ["equip.start_import"]          = "Start import",
        ["equip.importing"]             = "Importing...",
        ["equip.no_file"]               = "No file selected.",
        ["equip.complete"]              = "Import/registration complete.",
        ["equip.complete_desc"]         = "The equipment list has been updated below.",
        ["equip.complete_desc2"]        = "You can continue registering manually or import new files.",
        ["equip.previous"]              = "Previous",
        ["equip.next"]                  = "Next",
        ["equip.close"]                 = "Close",
        ["equip.list_title"]            = "Equipment",
        ["equip.search_placeholder"]    = "Tag, name, energy...",
        ["equip.found"]                 = "equipment found",
        ["equip.not_found"]             = "No equipment found",
        ["equip.col_identification"]    = "I. Identification",
        ["equip.col_energy_control"]    = "II. Energy control",
        ["equip.col_active"]            = "Active",
        ["equip.col_actions"]           = "Actions",
        ["equip.no_records"]            = "No equipment found for the selected plant.",
        ["equip.image_unavailable"]     = "Image not available.",
        ["equip.notes"]                 = "Notes",
        ["equip.no_notes"]              = "No notes found for this image.",
        ["equip.delete_confirm_text"]   = "Are you sure you want to delete equipment",
        ["equip.view_img_notes"]        = "View image and notes",
        // Import status
        ["equip.status.pending"]        = "Pending",
        ["equip.status.sent"]           = "Sent",
        ["equip.status.processing"]     = "Processing",
        ["equip.status.completed"]      = "Completed",
        ["equip.status.error"]          = "Error",
        // Toasts
        ["equip.toast.saved"]           = "Equipment saved successfully.",
        ["equip.toast.save_error"]      = "An error occurred while saving the equipment.",
        ["equip.toast.select_plant"]    = "Select a plant before saving.",
        ["equip.toast.no_permission"]   = "You don't have permission to register equipment in this plant.",
        ["equip.toast.no_perm_import"]  = "You don't have permission to import equipment in this plant.",
        ["equip.toast.no_user"]         = "User not identified.",
        ["equip.toast.select_advance"]  = "Select a plant before proceeding.",
        ["equip.toast.no_access"]       = "You don't have access to this plant.",
        ["equip.toast.select_import"]   = "Select a plant and file before importing.",
        ["equip.toast.deleted"]         = "Equipment marked as inactive.",
        ["equip.toast.delete_error"]    = "Error removing equipment.",
        ["equip.import.started"]        = "Import started...",
        ["equip.import.done_prefix"]    = "Import completed —",
        ["equip.import.files_ok"]       = "file(s) imported successfully.",
        ["equip.import.warnings"]       = "Completed with warnings —",
        ["equip.import.successes"]      = "success(es),",
        ["equip.import.errors"]         = "error(s). Check the details above.",
        ["equip.import.failed"]         = "Import failed —",
        ["equip.import.failed_desc"]    = "file(s) with error. Check the details above.",
        ["equip.import.error_table"]    = "file(s) with error. Check the details in the table.",
        ["equip.import.all_failed"]     = "All files failed. Check the details in the table.",
        // Template modal
        ["equip.tmpl.title"]            = "Expected Excel file structure (LOTOTO template)",
        ["equip.tmpl.warning"]          = "The file must be <strong>.xlsx</strong> and follow exactly this structure. Files with columns in different positions, required empty cells or incorrect format will be rejected with a detailed error message.",
        ["equip.tmpl.cell"]             = "Cell",
        ["equip.tmpl.column"]           = "Column",
        ["equip.tmpl.field"]            = "Field",
        ["equip.tmpl.required"]         = "Required",
        ["equip.tmpl.observation"]      = "Notes",
        ["equip.tmpl.yes"]              = "Yes",
        ["equip.tmpl.no"]               = "No",
        ["equip.tmpl.header_section"]   = "Header (row 3)",
        ["equip.tmpl.data_section"]     = "Data — from row 7 (file must have at least 14 columns A–N)",
        ["equip.tmpl.group1"]           = "Group I — Hazardous energy identification",
        ["equip.tmpl.group2"]           = "Group II — Hazardous energy control",
        ["equip.tmpl.visual_map"]       = "Column visual map (data row)",
        ["equip.tmpl.special_rules"]    = "Special rules",
        ["equip.tmpl.required_badge"]   = "⭐ Required",
        ["equip.tmpl.col_b_note"]       = "Column B (No.) must contain a positive integer in each risk row.",
        ["equip.tmpl.letter"]           = "Letter",
        // Header table rows
        ["equip.tmpl.tag_field"]        = "Equipment tag",
        ["equip.tmpl.tag_obs"]          = "Unique equipment identifier",
        ["equip.tmpl.name_field"]       = "Equipment name / description",
        ["equip.tmpl.name_obs"]         = "Descriptive name of the equipment",
        ["equip.tmpl.factory_field"]    = "Factory / Plant",
        ["equip.tmpl.factory_obs"]      = "Name of the factory or plant",
        ["equip.tmpl.revision_field"]   = "Revision / Date",
        ["equip.tmpl.revision_obs"]     = "Revision or date information for the document",
        // Group I rows
        ["equip.tmpl.g1_number_field"]  = "No. (line / risk)",
        ["equip.tmpl.g1_number_obs"]    = "Positive integer. Identifies each risk line. Lines without a number are ignored. Lines where cell A is merged to X/Y/Z/XFD are treated as comments.",
        ["equip.tmpl.g1_type_field"]    = "Energy type / Magnitude",
        ["equip.tmpl.g1_type_obs"]      = "Ex: Electrical, Pneumatic, Hydraulic…",
        ["equip.tmpl.g1_desc_field"]    = "Hazardous energy description",
        ["equip.tmpl.g1_desc_obs"]      = "Free text describing the hazard",
        ["equip.tmpl.g1_image_field"]   = "Photo / image",
        ["equip.tmpl.g1_image_obs"]     = "In-cell image or floating image in columns E–H. Multiple images on the same row are merged vertically.",
        // Group II rows
        ["equip.tmpl.g2_iso_tag_field"] = "Isolation device TAG",
        ["equip.tmpl.g2_iso_tag_obs"]   = "Device code/TAG",
        ["equip.tmpl.g2_loc_field"]     = "Device location",
        ["equip.tmpl.g2_loc_obs"]       = "Physical location of the device",
        ["equip.tmpl.g2_device_field"]  = "Isolation device",
        ["equip.tmpl.g2_device_obs"]    = "Description of the isolation device",
        ["equip.tmpl.g2_lockout_field"] = "Lockout",
        ["equip.tmpl.g2_lockout_obs"]   = "Type of lockout applied",
        ["equip.tmpl.g2_zero_field"]    = "Zero energy verification",
        ["equip.tmpl.g2_zero_obs"]      = "Zero energy verification method",
        ["equip.tmpl.g2_test_field"]    = "Test",
        ["equip.tmpl.g2_test_obs"]      = "Test procedure",
        // Visual map
        ["equip.tmpl.map_number"]       = "No.",
        ["equip.tmpl.map_energy_type"]  = "Energy type",
        ["equip.tmpl.map_desc"]         = "Description",
        ["equip.tmpl.map_photo"]        = "Photo",
        ["equip.tmpl.map_float_zone"]   = "Floating image zone (E–H)",
        ["equip.tmpl.map_iso_tag"]      = "Dev. TAG",
        ["equip.tmpl.map_location"]     = "Location",
        ["equip.tmpl.map_device"]       = "Device",
        ["equip.tmpl.map_lockout"]      = "Lockout",
        ["equip.tmpl.map_zero"]         = "Zero energy",
        ["equip.tmpl.map_test"]         = "Test",
        // Special rules
        ["equip.tmpl.rule_comments"]       = "Comment lines:",
        ["equip.tmpl.rule_comments_desc"]  = "Lines where cell A is merged to columns X, Y, Z, or XFD are ignored during parsing.",
        ["equip.tmpl.rule_floating"]       = "Floating images:",
        ["equip.tmpl.rule_floating_desc"]  = "Images over columns E–H associated with a risk line are extracted automatically. Multiple images on the same line are merged vertically.",
        ["equip.tmpl.rule_balloons"]       = "Note balloons (shapes):",
        ["equip.tmpl.rule_balloons_desc"]  = "Shapes with text in columns E–H are extracted as image notes.",
        ["equip.tmpl.rule_min_cols"]       = "Minimum columns:",
        ["equip.tmpl.rule_min_cols_desc"]  = "The file must have at least 14 columns (A–N).",
        ["equip.tmpl.rule_data_start"]     = "Data start:",
        ["equip.tmpl.rule_data_start_desc"]= "Data starts at row 7. Rows 1–6 are reserved for the template header.",
        ["equip.tmpl.rule_stop"]           = "Automatic stop:",
        ["equip.tmpl.rule_stop_desc"]      = "Parsing stops after 10 consecutive rows without a number in column B.",

        // ── PLE ────────────────────────────────────────────────────────
        ["nav.ple"]                  = "Lockout",
        ["ple.title"]                = "Energy Lockout",
        ["ple.new"]                  = "New Lockout",
        ["ple.edit"]                 = "Edit Lockout",
        ["ple.list"]                 = "Lockout List",
        ["ple.number"]               = "Number",
        ["ple.equipment"]            = "Equipment",
        ["ple.tag_disp"]             = "Disp. TAG",
        ["ple.department"]           = "Department",
        ["ple.operation"]            = "Operation",
        ["ple.description"]          = "Description",
        ["ple.start_date"]           = "Start Date",
        ["ple.end_date"]             = "End Date",
        ["ple.status"]               = "Status",
        ["ple.observations"]         = "Observations",
        ["ple.created_by"]           = "Created by",
        ["ple.modified_by"]          = "Modified by",
        ["ple.finalized_by"]         = "Finalized by",
        ["ple.created_at"]           = "Created at",
        ["ple.plant"]                = "Plant",
        ["ple.select_equipment"]     = "Select equipment...",
        ["ple.select_plant"]         = "Select plant...",

        // Status
        ["ple.status.criado"]        = "Created",
        ["ple.status.em_andamento"]  = "In Progress",
        ["ple.status.cancelado"]      = "Cancelled",
        ["ple.status.inicio_desbloqueio"] = "Unlock Start",
        ["ple.status.finalizado"]    = "Finalized",

        // State note shown in the PLE detail signal band. Descriptive:
        // it reports the physical situation, it does not issue a safety instruction.
        ["nav.panel"]                = "Panel",
        // Alerts panel / TV board
        ["mural.panel_title"]        = "Lockout/Unlock Panel",
        ["mural.state_blocked"]      = "Locked",
        ["mural.state_process"]      = "In process",
        ["mural.state_free"]         = "Free",
        ["mural.no_equipment"]       = "No equipment registered for this plant.",
        ["mural.none_blocked"]       = "No locked equipment at the moment.",
        ["mural.auto_refresh"]       = "Auto-refresh every {0} min",
        ["mural.updated_at"]         = "Updated at {0}",
        ["mural.plant_not_found"]    = "Plant not found",
        ["mural.loading"]            = "Loading...",
        ["mural.select_plant"]       = "Select a plant to view the panel.",
        ["mural.refresh"]            = "Refresh",
        ["mural.open_tv"]            = "Open TV version (fullscreen)",
        ["mural.tv"]                 = "TV",
        ["mural.leaders"]            = "Lockout leader(s)",
        ["mural.requests"]           = "Request(s)",

        ["ple.none_found"]                     = "No PLE found.",
        ["ple.legend"]                         = "Legend",
        ["ple.state_note.criado"]              = "Lockout not started yet.",
        ["ple.state_note.em_andamento"]        = "Energy isolated — lockout active.",
        ["ple.state_note.cancelado"]           = "PLE cancelled.",
        ["ple.state_note.inicio_desbloqueio"]  = "Unlock started.",
        ["ple.state_note.finalizado"]          = "Lockout closed.",

        // Wizard steps
        ["ple.step1"]                = "Identification",
        ["ple.step2"]                = "Risk Assessment",
        ["ple.step3"]                = "Review & Confirm",
        ["ple.step_of"]              = "of",

        // Items (Risk Assessment)
        ["ple.item.task"]            = "Task",
        ["ple.item.hazard"]          = "Hazard",
        ["ple.item.exposed"]         = "# Exposed",
        ["ple.item.severity_before"] = "Severity (before)",
        ["ple.item.probability_before"] = "Probability (before)",
        ["ple.item.risk_before"]     = "Risk Level (before)",
        ["ple.item.measures"]        = "Protective Measures",
        ["ple.item.severity_after"]  = "Severity (after)",
        ["ple.item.probability_after"] = "Probability (after)",
        ["ple.item.risk_after"]      = "Risk Level (after)",
        ["ple.item.add"]             = "Add Item",
        ["ple.item.remove"]          = "Remove",
        ["ple.item.before_reduction"]  = "Before Risk Reduction",
        ["ple.item.after_reduction"]   = "After Risk Reduction",

        // Severity / Probability / Risk
        ["ple.severity.catastrophic"] = "Catastrophic",
        ["ple.severity.serious"]      = "Serious",
        ["ple.severity.moderate"]     = "Moderate",
        ["ple.severity.minor"]        = "Minor",
        ["ple.probability.very_likely"] = "Very likely",
        ["ple.probability.likely"]      = "Likely",
        ["ple.probability.unlikely"]    = "Unlikely",
        ["ple.probability.remote"]      = "Remote",
        ["ple.risk.high"]              = "High",
        ["ple.risk.medium"]            = "Medium",
        ["ple.risk.low"]               = "Low",
        ["ple.risk.insignificant"]     = "Insignificant",

        // Actions
        ["ple.action.start"]         = "Start",
        ["ple.action.suspend"]       = "Suspend",
        ["ple.action.cancel_ple"]    = "Cancel Lockout",
        ["ple.cancel_reason"]        = "Cancellation Reason",
        ["ple.action.resume"]        = "Resume",
        ["ple.action.finalize"]      = "Finalize",
        ["ple.action.start_unlock"]  = "Unlock Start",
        ["ple.confirm_start_unlock"] = "Are you sure you want to start the unlock process? Central Command will be responsible for the final completion.",
        ["ple.action.delete"]        = "Delete",
        ["ple.action.print"]         = "Print",
        ["ple.action.save"]          = "Save",
        ["ple.action.cancel"]        = "Cancel",
        ["ple.action.next"]          = "Next",
        ["ple.action.previous"]      = "Previous",
        ["ple.action.confirm"]       = "Confirm",

        // Suspension
        ["ple.suspend_reason"]       = "Suspension Reason",
        ["ple.suspend_reason_required"] = "Please provide the reason for suspension",

        // History
        ["ple.history"]              = "History",
        ["ple.history.action"]       = "Action",
        ["ple.history.user"]         = "User",
        ["ple.history.date"]         = "Date/Time",
        ["ple.history.details"]      = "Details",
        ["ple.history.status_from"]  = "From",
        ["ple.history.status_to"]    = "To",

        // Toasts
        ["ple.toast.created"]        = "Lockout created successfully!",
        ["ple.toast.updated"]        = "Lockout updated successfully!",
        ["ple.toast.deleted"]        = "Lockout deleted successfully!",
        ["ple.toast.status_changed"] = "Lockout status changed successfully!",
        ["ple.toast.error"]          = "Error processing lockout.",
        ["ple.toast.cannot_edit"]    = "Cannot edit a finalized lockout.",

        // Filters
        ["ple.filter.all_status"]    = "All statuses",
        ["ple.filter.search"]        = "Search by number, equipment, department...",

        // Confirmation
        ["ple.confirm_delete"]       = "Are you sure you want to delete this lockout?",
        ["ple.confirm_finalize"]     = "Are you sure you want to finalize this lockout? Once finalized, it cannot be edited.",

        // Print
        ["ple.print.title"]          = "Energy Release Procedure",
        ["ple.print.copy"]           = "Copy",
        ["ple.print.copy1"]          = "1st Copy - Control",
        ["ple.print.copy2"]          = "2nd Copy - Field",

        // Maintenance badge
        ["ple.maintenance_badge"]    = "Lockout in progress",
        ["ple.maintenance_badge_active"] = "Active Lockout",
        ["ple.users_with_permission"] = "Users with permission",
        ["ple.users_with_permission_hint"] = "(optional — same permissions as creator)",
        ["ple.authorized_users"]      = "Authorized users",

        // ── Risk Assessment ────────────────────────────────────────────
        ["nav.risk_assessment"]       = "Risk Assessment",
        ["ar.title"]                  = "Risk Assessment — Alternative Method",
        ["ar.new"]                    = "New Assessment",
        ["ar.edit"]                   = "Edit Assessment",
        ["ar.list"]                   = "Risk Assessments",
        ["ar.none_found"]             = "No assessment found.",
        ["ar.number"]                 = "Number",
        ["ar.department"]             = "Department",
        ["ar.operation"]              = "Operation",
        ["ar.task"]                   = "Task / Description",
        ["ar.date"]                   = "Date",
        ["ar.observations"]           = "Observations",
        ["ar.status"]                 = "Status",
        ["ar.status.ativa"]        = "Active",
        ["ar.status.inativa"]       = "Inactive",
        ["ar.plant"]                  = "Plant",
        ["ar.select_plant"]           = "Select plant...",
        ["ar.created_by"]             = "Created by",
        ["ar.step1"]                  = "Identification",
        ["ar.step2"]                  = "Risk Assessment",
        ["ar.step3"]                  = "Review",
        ["ar.item.task"]              = "Task",
        ["ar.item.hazard"]            = "Hazard",
        ["ar.item.exposed"]           = "# Exposed",
        ["ar.item.severity_before"]   = "Severity (before)",
        ["ar.item.probability_before"]= "Probability (before)",
        ["ar.item.risk_before"]       = "Risk Level (before)",
        ["ar.item.measures"]          = "Protective Measures",
        ["ar.item.severity_after"]    = "Severity (after)",
        ["ar.item.probability_after"] = "Probability (after)",
        ["ar.item.risk_after"]        = "Risk Level (after)",
        ["ar.item.add"]               = "Add Item",
        ["ar.item.remove"]            = "Remove",
        ["ar.item.before_reduction"]  = "Before Risk Reduction",
        ["ar.item.after_reduction"]   = "After Risk Reduction",
        ["ar.action.save"]            = "Save",
        ["ar.action.cancel"]          = "Cancel",
        ["ar.action.conclude"]        = "Complete",
        ["ar.action.print"]           = "Print",
        ["ar.action.delete"]          = "Delete",
        ["ar.action.next"]            = "Next",
        ["ar.action.previous"]        = "Previous",
        ["ar.action.deactivate"]      = "Deactivate",
        ["ar.action.activate"]        = "Activate",
        ["ar.confirm_deactivate"]     = "Deactivate this assessment?",
        ["ar.deactivate_title"]       = "Deactivate",
        ["ar.toast.created"]          = "Assessment created successfully!",
        ["ar.toast.updated"]          = "Assessment updated successfully!",
        ["ar.toast.concluded"]        = "Assessment completed!",
        ["ar.toast.deleted"]          = "Assessment deleted!",
        ["ar.toast.error"]            = "Error processing assessment.",
        ["ar.toast.status_changed"]   = "Assessment status changed successfully!",
        ["ar.confirm_conclude"]       = "Complete this assessment? Once completed, it cannot be edited.",
        ["ar.confirm_delete"]         = "Delete this assessment?",
        ["ar.filter.all_status"]      = "All statuses",
        ["ar.filter.search"]          = "Search by number, department, task...",

        // ── Audit (#5b) ───────────────────────────────────────────────
        ["audit.title"]               = "Audit",
        ["audit.subtitle"]            = "System change trail",
        ["audit.filter.period_from"]  = "From",
        ["audit.filter.period_to"]    = "To",
        ["audit.filter.user"]         = "Executor user",
        ["audit.filter.entity"]       = "Entity",
        ["audit.filter.action"]       = "Action",
        ["audit.filter.all_users"]    = "All",
        ["audit.filter.all_entities"] = "All",
        ["audit.filter.all_actions"]  = "All",
        ["audit.filter.apply"]        = "Filter",
        ["audit.filter.clear"]        = "Clear",
        ["audit.col_when"]            = "When",
        ["audit.col_user"]            = "User",
        ["audit.col_entity"]          = "Entity",
        ["audit.col_key"]             = "Record",
        ["audit.col_action"]          = "Action",
        ["audit.col_details"]         = "Details",
        ["audit.action_create"]       = "Create",
        ["audit.action_update"]       = "Update",
        ["audit.action_delete"]       = "Delete",
        ["audit.no_results"]          = "No audit entries found for the selected filters.",
        ["audit.search_placeholder"]  = "Search by user, key or action...",
        ["audit.diff_title"]          = "Change — before and after",
        ["audit.diff_field"]          = "Field",
        ["audit.diff_before"]         = "Before",
        ["audit.diff_after"]          = "After",
        ["audit.unknown_user"]        = "—",

        // ── Users Report (#6a) ────────────────────────────────────────
        ["report.users.title"]        = "Users Report",
        ["report.users.subtitle"]     = "Consolidated active users",
        ["report.users.filter.plant"] = "Plant",
        ["report.users.filter.profile"] = "Profile",
        ["report.users.filter.bond"]  = "Bond",
        ["report.users.filter.status"] = "Validity status",
        ["report.users.filter.all"]   = "All",
        ["report.users.status_active"] = "Active",
        ["report.users.status_expiring"] = "Expiring (≤30d)",
        ["report.users.status_expired"] = "Expired",
        ["report.users.export_excel"] = "Export Excel",
        ["report.users.export_pdf"]   = "Export PDF",
        ["report.users.col_user"]     = "User",
        ["report.users.col_profiles"] = "Profiles",
        ["report.users.col_plants"]   = "Plants",
        ["report.users.col_bond"]     = "Bond",
        ["report.users.col_validity"] = "Access validity",
        ["report.users.col_training"] = "Training",
        ["report.users.col_last_login"] = "Last login",
        ["report.users.col_responsibles"] = "Responsibles",
        ["report.users.created_by_short"] = "Created by",
        ["report.users.updated_by_short"] = "Updated by",
        ["report.users.no_results"]   = "No users found for the selected filters.",
        ["report.users.search_placeholder"] = "Name, login, plant or company...",
        ["report.users.not_required"] = "Not required",

        // ── Revalidation Campaign (#6b) ───────────────────────────────
        ["campaign.title"]            = "Revalidation",
        ["campaign.subtitle"]         = "Periodic access review",
        ["campaign.new"]              = "New",
        ["campaign.name"]             = "Name",
        ["campaign.plants"]           = "Plants",
        ["campaign.due_date"]         = "Expected completion",
        ["campaign.periodicity"]      = "Periodicity",
        ["campaign.periodicity_monthly"] = "Monthly",
        ["campaign.periodicity_quarterly"] = "Quarterly",
        ["campaign.periodicity_biannual"] = "Biannual",
        ["campaign.periodicity_yearly"] = "Yearly",
        ["campaign.status"]           = "Status",
        ["campaign.status_planned"]   = "Planned",
        ["campaign.status_running"]   = "Running",
        ["campaign.status_completed"] = "Completed",
        ["campaign.status_cancelled"] = "Cancelled",
        ["campaign.start"]            = "Start",
        ["campaign.end_expected"]     = "Expected end",
        ["campaign.end_actual"]       = "End",
        ["campaign.progress"]         = "Progress",
        ["campaign.created_by"]       = "Created by",
        ["campaign.notes"]            = "Notes",
        ["campaign.no_results"]       = "No campaigns yet.",
        ["campaign.create_button"]    = "Create",
        ["campaign.detail_title"]     = "Access review",
        ["campaign.col_user"]         = "User",
        ["campaign.col_snapshot"]     = "Status at campaign start",
        ["campaign.col_decision"]     = "Decision",
        ["campaign.col_who"]          = "Decided by",
        ["campaign.col_when"]         = "When",
        ["campaign.col_note"]         = "Note",
        ["campaign.decision_keep"]    = "Keep",
        ["campaign.decision_adjust"]  = "Adjust",
        ["campaign.decision_revoke"]  = "Revoke (deactivate)",
        ["campaign.decision_pending"] = "Pending",
        ["campaign.filter.user"]      = "User",
        ["campaign.filter.decision"]  = "Decision",
        ["campaign.filter.all"]       = "All",
        ["campaign.filter.search_placeholder"] = "Name, login or summary...",
        ["campaign.save_decision"]    = "Save",
        ["campaign.complete"]         = "Complete",
        ["campaign.cancel"]           = "Cancel",
        ["campaign.cancel_yes"]       = "Yes, cancel",
        ["campaign.cancel_confirm"]   = "Cancel this campaign?",
        ["campaign.toast.created"]    = "Campaign created and managers notified.",
        ["campaign.toast.decided"]    = "Decision saved.",
        ["campaign.toast.completed"]  = "Campaign completed.",
        ["campaign.toast.cancelled"]  = "Campaign cancelled.",
        ["campaign.toast.name_required"] = "Enter the campaign name.",
        ["campaign.toast.plants_required"] = "Select at least one plant.",
        ["campaign.toast.due_required"] = "Enter the expected completion date.",
    };
}
