// <auto-generated />
using System;
using EToto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EToto.Infrastructure.Migrations
{
    [DbContext(typeof(LototoContext))]
    [Migration("20260616151119_AdicionarMultiplosPerfisPorUsuario")]
    partial class AdicionarMultiplosPerfisPorUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRisco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tarefa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("AvaliacaoRisco", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRiscoEquipamento", b =>
                {
                    b.Property<Guid>("AvaliacaoRiscoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AvaliacaoRiscoId", "EquipamentoId");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("AvaliacaoRiscoEquipamento", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRiscoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("AvaliacaoRiscoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoRiscoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AvaliacaoRiscoHistorico", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRiscoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AvaliacaoRiscoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GravidadeAntes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GravidadeDepois")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedidasProtecao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NivelRiscoAntes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NivelRiscoDepois")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroExpostos")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Perigo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProbabilidadeAntes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProbabilidadeDepois")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tarefa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoRiscoId");

                    b.ToTable("AvaliacaoRiscoItem", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.Equipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EnergyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HazardDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageBlobUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IsolationDeviceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsolationDeviceLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsolationDeviceTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("LockoutType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<string>("RevisionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceExcelBlobUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Test")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZeroEnergyVerification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("PlantaId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Equipamento", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.Plantas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Plantas", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.Ple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalizadoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MotivoCancelamento");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("FinalizadoPorId");

                    b.HasIndex("ModificadoPorId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PlantaId");

                    b.ToTable("Ple", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.PleEquipamento", b =>
                {
                    b.Property<Guid>("PleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PleId", "EquipamentoId");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("PleEquipamento", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.PleHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusNovo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PleId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PleHistorico", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.PleUsuarioPermitido", b =>
                {
                    b.Property<Guid>("PleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PleId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PleUsuarioPermitido", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAssociacao")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "Perfil");

                    b.ToTable("UsuarioPerfis", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.UsuarioPlanta", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAssociacao")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "PlantaId");

                    b.HasIndex("PlantaId");

                    b.ToTable("UsuarioPlantas", (string)null);
                });

            modelBuilder.Entity("EToto.Domain.Entities.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AlteradoPorId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTreinamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<int?>("PlantaId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TreinamentoConcluido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlteradoPorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("PlantaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRisco", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Usuarios", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Usuarios", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CriadoPor");

                    b.Navigation("ModificadoPor");
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRiscoEquipamento", b =>
                {
                    b.HasOne("EToto.Domain.Entities.AvaliacaoRisco", "AvaliacaoRisco")
                        .WithMany("Equipamentos")
                        .HasForeignKey("AvaliacaoRiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvaliacaoRisco");

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRiscoHistorico", b =>
                {
                    b.HasOne("EToto.Domain.Entities.AvaliacaoRisco", "AvaliacaoRisco")
                        .WithMany("Historico")
                        .HasForeignKey("AvaliacaoRiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvaliacaoRisco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRiscoItem", b =>
                {
                    b.HasOne("EToto.Domain.Entities.AvaliacaoRisco", "AvaliacaoRisco")
                        .WithMany("Itens")
                        .HasForeignKey("AvaliacaoRiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvaliacaoRisco");
                });

            modelBuilder.Entity("EToto.Domain.Entities.Equipamento", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Usuarios", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EToto.Domain.Entities.Plantas", "Planta")
                        .WithMany("Equipamentos")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Usuarios", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Planta");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("EToto.Domain.Entities.Ple", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Usuarios", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Usuarios", "FinalizadoPor")
                        .WithMany()
                        .HasForeignKey("FinalizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EToto.Domain.Entities.Usuarios", "ModificadoPor")
                        .WithMany()
                        .HasForeignKey("ModificadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EToto.Domain.Entities.Plantas", "Planta")
                        .WithMany()
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("FinalizadoPor");

                    b.Navigation("ModificadoPor");

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("EToto.Domain.Entities.PleEquipamento", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Ple", "Ple")
                        .WithMany("Equipamentos")
                        .HasForeignKey("PleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Ple");
                });

            modelBuilder.Entity("EToto.Domain.Entities.PleHistorico", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Ple", "Ple")
                        .WithMany("Historico")
                        .HasForeignKey("PleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ple");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EToto.Domain.Entities.PleUsuarioPermitido", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Ple", "Ple")
                        .WithMany("UsuariosPermitidos")
                        .HasForeignKey("PleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ple");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EToto.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Usuarios", "Usuario")
                        .WithMany("Perfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EToto.Domain.Entities.UsuarioPlanta", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Plantas", "Planta")
                        .WithMany("UsuariosAssociados")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EToto.Domain.Entities.Usuarios", "Usuario")
                        .WithMany("PlantasAssociadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EToto.Domain.Entities.Usuarios", b =>
                {
                    b.HasOne("EToto.Domain.Entities.Usuarios", "AlteradoPor")
                        .WithMany()
                        .HasForeignKey("AlteradoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EToto.Domain.Entities.Usuarios", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EToto.Domain.Entities.Plantas", "Planta")
                        .WithMany("Usuarios")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AlteradoPor");

                    b.Navigation("CriadoPor");

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("EToto.Domain.Entities.AvaliacaoRisco", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Historico");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("EToto.Domain.Entities.Plantas", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Usuarios");

                    b.Navigation("UsuariosAssociados");
                });

            modelBuilder.Entity("EToto.Domain.Entities.Ple", b =>
                {
                    b.Navigation("Equipamentos");

                    b.Navigation("Historico");

                    b.Navigation("UsuariosPermitidos");
                });

            modelBuilder.Entity("EToto.Domain.Entities.Usuarios", b =>
                {
                    b.Navigation("Perfis");

                    b.Navigation("PlantasAssociadas");
                });
#pragma warning restore 612, 618
        }
    }
}
