name: Deploy DEMO - e-toto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ./EToto.Web/EToto.Web.csproj

      - name: Build
        run: dotnet build ./EToto.Web/EToto.Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./EToto.Web/EToto.Web.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure Web App (DEMO)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'e-toto'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_ETOTO }}
          package: ./publish
